---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: echo-server
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: ealenn-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/ealen/echo-server
      tag: 0.5.1
    ingress:
      enabled: true
      annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "video-input-antenna"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "echo-server.${SECRET_DOMAIN}"
          paths:
            - "/"
      tls:
        - secretName: echo-server-tls
          hosts:
            - "echo-server.${SECRET_DOMAIN}"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
