---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: promtail
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: k8s-at-home/promtail

    config:
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:1514
              label_structured_data: true
              labels:
                job: syslog
            relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: host

    extraPorts:
      syslog:
        name: syslog
        containerPort: 1514
        service:
          type: LoadBalancer
          externalIPs:
            - ${LB_SYSLOG}

    serviceMonitor:
      enabled: true

    tolerations:
      - key: "arch"
        operator: "Equal"
        value: "arm64"
        effect: "NoSchedule"
