---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file: bootstrap/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
area/taskfile:
  - changed-files:
      - any-glob-to-any-file: .taskfiles/**/*
      - any-glob-to-any-file: Taskfile*
