[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true } # required:template
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_CONFIG = "{{config_root}}/.sops.yaml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
JUST_UNSTABLE = "1"

[tools]
python = "3.14.5"          # required:template
uv = "0.11.16"             # required:template
pipx = "1.12.0"            # required:template
"pipx:makejinja" = "2.8.2" # required:template
age = "1.3.1"
cloudflared = "2026.5.0"
cue = "0.16.1"             # required:template
flux2 = "2.8.8"
gh = "2.92.0"
gum = "0.17.0"
helm = "4.2.0"
helmfile = "1.5.2"
jq = "1.8.1"
just = "1.51.0"
kubeconform = "0.7.0"
kubectl = "1.36.1"
kustomize = "5.8.1"
lefthook = "2.1.8"
sd = "1.1.0"               # required:template
sops = "3.13.1"
talhelper = "3.1.10"
talosctl = "1.13.2"
yq = "4.53.2"
zizmor = "1.25.2"

[hooks]
postinstall = "lefthook install"
