---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  # Files
  BOOTSTRAP_ADDONS_FILE: "{{.BOOTSTRAP_DIR}}/vars/addons.yaml"
  BOOTSTRAP_CONFIG_FILE: "{{.BOOTSTRAP_DIR}}/vars/config.yaml"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  MAKEJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/makejinja.toml"
  PYTHON_VERSION_CHECK_FILE: "{{.BOOTSTRAP_DIR}}/scripts/py_version_check.py"
  SOPS_AGE_FILE: "{{.ROOT_DIR}}/age.key"
  # Binaries
  PYTHON_BIN: python3

includes:
  ansible: .taskfiles/Ansible/Taskfile.yaml
  kubernetes:
    aliases: ["k8s"]
    taskfile: .taskfiles/Kubernetes/Taskfile.yaml
  flux: .taskfiles/Flux/Taskfile.yaml
  k0s: .taskfiles/K0s/Taskfile.yaml
  repository:
    aliases: ["repo"]
    taskfile: .taskfiles/Repository/Taskfile.yaml
  talos: .taskfiles/Talos/Taskfile.yaml
  sops: .taskfiles/Sops/Taskfile.yaml
  workstation: .taskfiles/Workstation/Taskfile.yaml

tasks:

  default: task -l

  init:
    desc: Initialize files and directories
    cmds:
      - mkdir -p {{.PRIVATE_DIR}}
      - cp -n {{.BOOTSTRAP_ADDONS_FILE | replace ".yaml" ".sample.yaml"}} {{.BOOTSTRAP_ADDONS_FILE}}
      - cp -n {{.BOOTSTRAP_CONFIG_FILE | replace ".yaml" ".sample.yaml"}} {{.BOOTSTRAP_CONFIG_FILE}}
      - cmd: echo === Configuration files copied ===
        silent: true
      - cmd: echo Proceed with updating the configuration files...
        silent: true
      - cmd: echo {{.BOOTSTRAP_CONFIG_FILE}}
        silent: true
      - cmd: echo {{.BOOTSTRAP_ADDONS_FILE}}
        silent: true
    status:
      - test -f {{.BOOTSTRAP_ADDONS_FILE}}
      - test -f {{.BOOTSTRAP_CONFIG_FILE}}

  configure:
    desc: Configure repository from Ansible vars
    prompt: Any conflicting config in the root kubernetes and ansible directories will be overwritten... continue?
    cmds:
      - task: .pre-validate
      - task: .template
      - task: .post-validate
    preconditions:
      - { msg: "Missing Python version check script", sh: "test -f {{.PYTHON_VERSION_CHECK_FILE}}" }
      - { msg: "Python version must be 3.11 or greater", sh: "{{.PYTHON_BIN}} {{.PYTHON_VERSION_CHECK_FILE}}" }

  .pre-validate:
    internal: true
    cmd: ./.venv/bin/ansible-playbook {{.BOOTSTRAP_DIR}}/validate.yaml
    env:
      ANSIBLE_DISPLAY_SKIPPED_HOSTS: "false"
    preconditions:
      - { msg: "Missing virtual environment", sh: "test -d {{.ROOT_DIR}}/.venv" }
      - { msg: "Missing bootstrap addons file", sh: "test -f {{.BOOTSTRAP_ADDONS_FILE}}" }
      - { msg: "Missing bootstrap config file", sh: "test -f {{.BOOTSTRAP_CONFIG_FILE}}" }

  .template:
    internal: true
    cmds:
      - ./.venv/bin/makejinja
      - task: sops:encrypt
    preconditions:
      - { msg: "Missing Makejinja config file", sh: "test -f {{.MAKEJINJA_CONFIG_FILE}}" }
      - { msg: "Missing Makejinja loader file", sh: "test -f {{.BOOTSTRAP_DIR}}/scripts/loader.py" }

  .post-validate:
    internal: true
    cmds:
      - task: kubernetes:kubeconform
