---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

set: [pipefail]
shopt: [globstar]

vars:
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  PRIVATE_DIR: '{{.ROOT_DIR}}/.private'
  TALHELPER_DIR: '{{.ROOT_DIR}}/kubernetes/bootstrap/talos'
  TALOSCONFIG: '{{.ROOT_DIR}}/kubernetes/bootstrap/talos/clusterconfig/talosconfig'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'
  TALOSCONFIG: '{{.TALOSCONFIG}}'

includes:
  bootstrap: .taskfiles/bootstrap
  kubernetes: .taskfiles/kubernetes
  talos: .taskfiles/talos
  template: .taskfiles/template

tasks:

  default: task --list
