---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"
  PACKER_DIR: "{{.PROJECT_DIR}}provision/packer"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/provision/terraform"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/provision/kubeconfig"
  PACKER_VARS_FILE: "{{.PROJECT_DIR}}/provision/vars.pkr.hcl"
  PACKER_BUILD_TEMPLATE: "{{.PROJECT_DIR}}/provision/template.pkr.hcl"

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  cluster: .taskfiles/ClusterTasks.yml
  packer: .taskfiles/PackerTasks.yml
  precommit: .taskfiles/PrecommitTasks.yml
  terraform: .taskfiles/TerraformTasks.yml

tasks:

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
      - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew is not installed. Using MacOS, Linux or WSL?
          Head over to https://brew.sh to get up and running.
    vars:
      DEPS: >-
        age
        ansible
        direnv
        fluxcd/tap/flux
        gitleaks
        go-task/tap/go-task
        helm
        ipcalc
        jq
        kubernetes-cli
        kustomize
        packer
        pre-commit
        prettier
        sops
        stern
        terraform
        yamllint
        yq

  verify:
    desc: Verify env settings
    cmds:
      - ./configure --verify

  configure:
    desc: Configure repository from env settings
    cmds:
      - ./configure
