---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: security
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:2.6.3
          imagePullPolicy: "Always"
          env:
            - name: LDAP_ROOT
              value: ${SECRET_LDAP_BASE_DN}
            - name: LDAP_ADMIN_USERNAME
              value: ${SECRET_LDAP_ADMIN_USERNAME}
            - name: LDAP_ADMIN_PASSWORD
              value: ${SECRET_LDAP_ADMIN_PASSWORD}
            - name: LDAP_CUSTOM_LDIF_DIR
              value: "/ldifs"
          ports:
            - name: tcp-ldap
              containerPort: 1389
          volumeMounts:
            - name: users-ldif
              mountPath: "/ldifs"
              readOnly: true
      volumes:
        - name: users-ldif
          secret:
            secretName: openldap
            items:
              - key: 01-default-users.ldif
                path: 01-default-users.ldif
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: security
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tcp-ldap
      port: 1389
      targetPort: tcp-ldap
  selector:
    app.kubernetes.io/name: openldap
