---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: error-pages
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 2.16.0
    env:
      TEMPLATE_NAME: lost-in-space
      SHOW_DETAILS: "false"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 250Mi
