---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  ref:
    # renovate: datasource=github-releases depName=fluxcd/flux2
    tag: "v0.31.3"
  url: https://github.com/fluxcd/flux2
  ignore: |
    # exclude all
    /*
    # path to manifests
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-installation
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-installation
