---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/base
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
