---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: system-upgrade
spec:
  interval: 15m
  chart:
    spec:
      chart: kured
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    configuration:
      startTime: "10pm"
      endTime: "2am"
      logFormat: "json"
      timeZone: "${TIMEZONE}"
      rebootSentinelCommand: |-
        sh -c "! needs-restarting --reboothint"
