[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true } # required:template
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_CONFIG = "{{config_root}}/.sops.yaml"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
JUST_UNSTABLE = "1"

[tools]
python = "3.14.6"          # required:template
uv = "0.11.26"             # required:template
pipx = "1.15.0"            # required:template
"pipx:makejinja" = "2.8.2" # required:template
age = "1.3.1"
cloudflared = "2026.6.1"
cue = "0.17.0"             # required:template
flux2 = "2.9.0"
gh = "2.96.0"
gum = "0.17.0"
helm = "4.2.2"
helmfile = "1.6.0"
jq = "1.8.2"
just = "1.55.1"
kubeconform = "0.8.0"
kubectl = "1.36.2"
kustomize = "5.8.1"
lefthook = "2.1.9"
oxfmt = "0.57.0"
sd = "1.1.0"               # required:template
sops = "3.13.2"
talhelper = "3.1.12"
talosctl = "1.13.5"
yq = "4.53.3"
zizmor = "1.26.1"

[hooks]
postinstall = "lefthook install"
