---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: kured
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    configuration:
      annotateNodes: true
      startTime: "10pm"
      endTime: "2am"
      logFormat: "json"
      rebootCommand: "/bin/systemctl reboot"
      timeZone: "${TIMEZONE}"
