---
name: "e2e"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - kubernetes/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    if: ${{ github.repository == 'onedr0p/cluster-template' }}
    name: configure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config-files:
          - public
          - private
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          cache: false

      - name: Run init task
        run: task init

      - name: Prepare files
        run: |
          cp ./.github/tests/${{ matrix.config-files }}.yaml cluster.yaml
          cp ./.github/tests/nodes.yaml nodes.yaml
          echo '{"AccountTag":"fake","TunnelSecret":"fake","TunnelID":"fake"}' > cloudflare-tunnel.json
          touch kubeconfig

      - name: Run configure task
        run: task configure --yes

      - name: Run generate talconfig task
        run: |
          FILENAME=talos/talsecret.sops.yaml
          talhelper gensecret | sops --filename-override $FILENAME --encrypt /dev/stdin > $FILENAME
          task talos:generate-config

      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v8.2.0@sha256:9c77739d8d7c71b808311693ea52d603d1ddb5190d3d4f23e47f6f33d5254602
        with:
          args: test --enable-helm --all-namespaces --path /github/workspace/kubernetes/flux/cluster -v

      - name: Dry run bootstrap talos task
        run: task bootstrap:talos --dry

      - name: Dry run bootstrap apps task
        run: task bootstrap:apps --dry

      - name: Run reset task
        run: task template:reset --yes

      - name: Run cleanup task
        run: task template:tidy --yes
